import type { TourStep as BaseTourStep } from '@/types/tourTypes';

// Tabs constants
export const TABS = {
  VARIABLES: 'variables' as const,
  CATEGORICAL: 'categorical' as const,
  SAVE: 'save' as const,
  OPTIONS: 'options' as const,
  ASSUMPTION: 'assumption' as const,
};

export type TabType =
  | typeof TABS.VARIABLES
  | typeof TABS.CATEGORICAL
  | typeof TABS.SAVE
  | typeof TABS.OPTIONS
  | typeof TABS.ASSUMPTION;

export type TourStep = BaseTourStep & {
  requiredTab?: TabType;
  forceChangeTab?: boolean;
};

export const baseTourSteps: TourStep[] = [
  // ---------------- VARIABLES TAB ----------------
  {
    title: 'Variables Tab',
    content: 'Start here: select your dependent variable, covariates, and regression method. This defines what goes into the model.',
    targetId: 'binary-logistic-variables-tab-trigger',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📊',
    requiredTab: TABS.VARIABLES,
    forceChangeTab: true,
  },
  {
    title: 'Available Variables',
    content: 'Every variable in your dataset appears here. Click one (or drag it) into the Dependent or Covariates box on the right.',
    targetId: 'binary-logistic-available-variables-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📋',
    requiredTab: TABS.VARIABLES,
    forceChangeTab: true,
  },
  {
    title: 'Dependent Variable',
    content: 'The binary outcome you want to predict (e.g., Yes/No, Churn/No churn). It must have exactly two unique values.',
    targetId: 'binary-logistic-dependent-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🎯',
    requiredTab: TABS.VARIABLES,
    forceChangeTab: true,
  },
  {
    title: 'Covariates',
    content: 'The predictors used to explain the dependent variable. Nominal/ordinal covariates are auto-flagged for categorical coding on the Categorical tab.',
    targetId: 'binary-logistic-covariates-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📈',
    requiredTab: TABS.VARIABLES,
    forceChangeTab: true,
  },
  {
    title: 'Method',
    content: 'Enter includes all covariates at once. Forward/Backward Stepwise (Conditional, LR, or Wald) add or remove predictors automatically based on statistical criteria.',
    targetId: 'method-select',
    defaultPosition: 'top',
    defaultHorizontalPosition: null,
    icon: '🔀',
    requiredTab: TABS.VARIABLES,
    forceChangeTab: true,
  },

  // ---------------- CATEGORICAL TAB ----------------
  {
    title: 'Categorical Tab',
    content: 'Tell the model which covariates are categorical (nominal/ordinal) and how they should be coded.',
    targetId: 'binary-logistic-categorical-tab-trigger',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🏷️',
    requiredTab: TABS.CATEGORICAL,
    forceChangeTab: true,
  },
  {
    title: 'Categorical Covariates',
    content: 'Check any covariate that is categorical. Click a checked item again to edit its contrast method and reference category.',
    targetId: 'binary-logistic-categorical-list-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📋',
    requiredTab: TABS.CATEGORICAL,
    forceChangeTab: true,
  },
  {
    title: 'Contrast Method',
    content: 'Choose how the selected variable\'s categories are coded: Indicator, Simple, Difference, Helmert, Repeated, Polynomial, or Deviation.',
    targetId: 'binary-logistic-contrast-method-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🔢',
    requiredTab: TABS.CATEGORICAL,
    forceChangeTab: true,
  },
  {
    title: 'Reference Category',
    content: 'For contrasts that need a baseline, pick whether the First (lowest) or Last (highest) category is the reference, then click Change to apply.',
    targetId: 'binary-logistic-reference-category-box',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📌',
    requiredTab: TABS.CATEGORICAL,
    forceChangeTab: true,
  },

  // ---------------- SAVE TAB ----------------
  {
    title: 'Save Tab',
    content: 'Choose which model results should be written back into your dataset as new variables.',
    targetId: 'binary-logistic-save-tab-trigger',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '💾',
    requiredTab: TABS.SAVE,
    forceChangeTab: true,
  },
  {
    title: 'Predicted Values',
    content: 'Save the model-predicted probability for each case, and/or the predicted group membership (0/1).',
    targetId: 'binary-logistic-save-predicted-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📈',
    requiredTab: TABS.SAVE,
    forceChangeTab: true,
  },
  {
    title: 'Influence',
    content: 'Save diagnostics that flag cases with a disproportionate effect on the model: Cook\'s distance, leverage values, and DfBeta(s).',
    targetId: 'binary-logistic-save-influence-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '⚠️',
    requiredTab: TABS.SAVE,
    forceChangeTab: true,
  },
  {
    title: 'Residuals',
    content: 'Save the difference between observed and predicted outcomes, in unstandardized, logit, studentized, standardized, or deviance form.',
    targetId: 'binary-logistic-save-residuals-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📉',
    requiredTab: TABS.SAVE,
    forceChangeTab: true,
  },

  // ---------------- OPTIONS TAB ----------------
  {
    title: 'Options Tab',
    content: 'Fine-tune the statistics, plots, and convergence settings used when the model runs.',
    targetId: 'binary-logistic-options-tab-trigger',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '⚙️',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Statistics and Plots',
    content: 'Add classification plots, the Hosmer-Lemeshow goodness-of-fit test, casewise residual listings, correlations of estimates, iteration history, and a confidence interval for exp(B).',
    targetId: 'binary-logistic-options-stats-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📊',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Display',
    content: 'Show results at each step of a stepwise method, or only once at the last step when the final model is reached.',
    targetId: 'binary-logistic-options-display-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🖥️',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Probability for Stepwise',
    content: 'Set the significance thresholds a variable must meet to enter (Entry) or leave (Removal) the model during stepwise selection.',
    targetId: 'binary-logistic-options-stepwise-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🎚️',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Classification Cutoff',
    content: 'The predicted-probability threshold (default 0.5) used to classify a case into group 0 or group 1.',
    targetId: 'binary-logistic-options-cutoff-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '✂️',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Maximum Iterations',
    content: 'The maximum number of iterations the estimation algorithm is allowed to run before it stops.',
    targetId: 'binary-logistic-options-maxiter-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🔁',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },
  {
    title: 'Model Constant',
    content: 'Include or exclude the intercept (constant) term in the logistic regression equation.',
    targetId: 'binary-logistic-options-model-card',
    defaultPosition: 'top',
    defaultHorizontalPosition: null,
    icon: '➕',
    requiredTab: TABS.OPTIONS,
    forceChangeTab: true,
  },

  // ---------------- ASSUMPTION TAB ----------------
  {
    title: 'Assumption Tab',
    content: 'Check the statistical assumptions behind binary logistic regression before trusting the results.',
    targetId: 'binary-logistic-assumption-tab-trigger',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '✅',
    requiredTab: TABS.ASSUMPTION,
    forceChangeTab: true,
  },
  {
    title: 'Selected Variables',
    content: 'A quick summary of the dependent variable and covariates currently selected on the Variables tab.',
    targetId: 'binary-logistic-assumption-summary-card',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '📋',
    requiredTab: TABS.ASSUMPTION,
    forceChangeTab: true,
  },
  {
    title: 'Multicollinearity (VIF)',
    content: 'Checks whether covariates are too strongly correlated with each other, which can destabilize the model. Requires one dependent and at least two covariates.',
    targetId: 'binary-logistic-assumption-vif-section',
    defaultPosition: 'bottom',
    defaultHorizontalPosition: null,
    icon: '🔗',
    requiredTab: TABS.ASSUMPTION,
    forceChangeTab: true,
  },
  {
    title: 'Linearity of Logit (Box-Tidwell)',
    content: 'Tests whether continuous covariates have a linear relationship with the log-odds of the outcome, a key assumption of logistic regression.',
    targetId: 'binary-logistic-assumption-boxtidwell-section',
    defaultPosition: 'top',
    defaultHorizontalPosition: null,
    icon: '🌊',
    requiredTab: TABS.ASSUMPTION,
    forceChangeTab: true,
  },
];
